name: Build CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.1
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm run build
        env:
          PRO_COMPONENTS_CI: CI
      - run: pnpm run deploy:docs

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: xbeeant/ant-mini
          tags: latest

      - name: zip zite
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ant-mini_site.zip docs-dist

      - name: Generate release tag
        id: tag
        run: |
          echo "release_tag=sites_$(date +"%Y.%m.%d_%H_%M_%S")" >> $GITHUB_OUTPUT

      - name: GH Release
        # You may pin to the exact commit or the version.
        # uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: ant-mini_site.zip
