name: pull_request ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: build
        run: |
          npm i
          npm run build
          npm run check-compiled
      - name: test
        run: npm run cov
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          directory: ./coverage/
